version = 1

test_patterns = ["tests/*"]

exclude_patterns = [
  "foo.py",
  "foo/bar*.py",
  "baz.py"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "secrets"
enabled = true